spring.application.name=meetings
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/meetings

spring.datasource.username=meetings_user
spring.datasource.password=meetings_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration